### ISSUE TITLE
To extend WinControl.GetAttribute method

### ISSUE THREAD

**Issue by lollard** [Unicorn-TAF/ui-win#18]
/// <summary>
        /// Gets control attribute value as <see cref="string"/>
        /// </summary>
        /// <param name="attribute">attribute name</param>
        /// <returns>control attribute value as string</returns>
        public string GetAttribute(string attribute)
        {
            int id;
            switch (attribute.ToLower())
            {
                case "class":
                    id = UIA_PropertyIds.UIA_ClassNamePropertyId;
                    break;
                case "id":
                    id = UIA_PropertyIds.UIA_AutomationIdPropertyId;
                    break;
                case "name":
                    id = UIA_PropertyIds.UIA_NamePropertyId;
                    break;
                default:
                    throw new ArgumentException($"No such property as {attribute}");
            }
            return (string)Instance.GetCurrentPropertyValue(id);
        }

**Comment by dobriyanchik** [comment]
implemented in #19
